# Hartree-Fock - Nucleus-Nucleus repulsion

The energy contribution due to the repulsion between nuclei will be only a number because nuclei are instantaneously fixed in space (BO Approximation)

This energy, in atomic units is 

$$E_{NN} = \sum_{I=1}^{M} \sum_{J>I}^{M} \frac{Z_I Z_J}{R_{IJ}}$$


In [1]:
import numpy as np 
from Utils import * # Import functions from the previous notebooks

In [2]:
def nuclear_nuclear_repulsion(atom_coords, Z): 
    
    n_atoms = len(Z) # Number of atoms
    E_NN = 0 
    
    for i in range(n_atoms):
        for j in range(n_atoms):
            if j>i:
                r_ij_vec = atom_coords[i]-atom_coords[j] # Nuclear distance vector
                r_ij = np.sqrt(np.dot(r_ij_vec,r_ij_vec)) # Nuclear distance
                E_NN += Z[i]*Z[j]/r_ij # Repulsion energy
                
    return E_NN            

In [4]:
# STO-3G BASIS FOR 1S ORBITALS
atom_coords = [np.array([0,0,0]),np.array([0,0,1.4])]
Z = [1.,1.]

# Molecule
molecule = []

for i in range(len(Z)):
    molecule.append( [ primitive_gaussian(0.3425250914E+01,0.1543289673E+00,atom_coords[i]),
                       primitive_gaussian(0.6239137298E+00,0.5353281423E+00,atom_coords[i]),
                       primitive_gaussian(0.1688554040E+00,0.4446345422E+00,atom_coords[i])] )

print("STO-3G for 1s orbitals in H2")

# Overlap matrix
print("\n Overlap: \n",overlap(molecule))

# Kinetic energy matrix
print("\n Kinetic Energy: \n",kinetic(molecule))

# Electron-Nuclei attraction
print("\n Electron-Nuclei attraction: \n", electron_nuclear_attraction(molecule,atom_coords,Z))

# Electron - Electron repulsion
print("\n Electron-Electron repulsion: \n", electron_electron_repulsion(molecule))

# Nuclear - Nuclear repulsion
print("\n Nuclear-Nuclear repulsion: \n", nuclear_nuclear_repulsion(atom_coords,Z))

STO-3G for 1s orbitals in H2

 Overlap: 
 [[1.         0.65931821]
 [0.65931821 1.        ]]

 Kinetic Energy: 
 [[0.76003188 0.23645466]
 [0.23645466 0.76003188]]

 Electron-Nuclei attraction: 
 [[-1.88044089 -1.19483462]
 [-1.19483462 -1.88044089]]

 Electron-Electron repulsion: 
 [[[[0.77460594 0.44410766]
   [0.44410766 0.56967593]]

  [[0.44410766 0.29702854]
   [0.29702854 0.44410766]]]


 [[[0.44410766 0.29702854]
   [0.29702854 0.44410766]]

  [[0.56967593 0.44410766]
   [0.44410766 0.77460594]]]]

 Nuclear-Nuclear repulsion: 
 0.7142857142857143
